version: '3.8'
services:
  mongo-db:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - libros-net

  api-libros:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/biblioteca
    depends_on:
      - mongo-db
    networks:
      - libros-net

networks:
  libros-net:
    driver: bridge